(function () {
    "use strict";

    // Each of these sample groups must have a unique key to be displayed
    // separately.
    var sampleGroups = [
        { key: "group1", title: "Group 1", description: "Latest News" },
        { key: "group2", title: "Group 2", description: "Most Read Articles" },
        { key: "group3", title: "Group 3", description: "Recent Activity" },
        { key: "group4", title: "Group 4", description: "The Week in Photos" }
    ];

    // Each of these sample items should have a reference to a particular
    // group.
    var sampleItems = [
        { group: sampleGroups[0], backgroundColor: '#ff6a00', imageUrl: '', subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit', description: 'Donec elementum ipsum nunc, sit amet placerat lacus. Etiam eu rutrum quam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam tempor, urna sed ullamcorper volutpat, libero orci malesuada lacus, ut fringilla enim mi sed eros. Cras sit amet massa eu mauris accumsan semper eget et massa. In eget ipsum a mi elementum molestie. Ut facilisis orci eget leo pretium ut iaculis lorem mattis. Praesent nec leo a metus euismod suscipit quis at tortor. Nulla ut justo leo, id luctus orci. Aliquam nec enim eget enim aliquam mattis sed et purus. Integer gravida lorem non erat mattis ac aliquam augue ullamcorper. Cras vel suscipit lorem. Nulla facilisi. Duis ut est enim, sed tempus massa. Praesent massa eros, egestas ut tincidunt vel, elementum vitae libero. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae. Donec ut semper enim. In pellentesque malesuada adipiscing. Cras ullamcorper urna sed leo iaculis molestie. Proin urna ipsum, congue ut dignissim ut, consectetur id sem. Nulla felis dui, fringilla suscipit dapibus non, mattis ut lectus. Suspendisse potenti. Quisque porttitor porttitor cursus.' },
        { group: sampleGroups[0], backgroundColor: '#ff006e', imageUrl: '', subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit', description: 'Donec elementum ipsum nunc, sit amet placerat lacus. Etiam eu rutrum quam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam tempor, urna sed ullamcorper volutpat, libero orci malesuada lacus, ut fringilla enim mi sed eros. Cras sit amet massa eu mauris accumsan semper eget et massa. In eget ipsum a mi elementum molestie. Ut facilisis orci eget leo pretium ut iaculis lorem mattis. Praesent nec leo a metus euismod suscipit quis at tortor. Nulla ut justo leo, id luctus orci. Aliquam nec enim eget enim aliquam mattis sed et purus. Integer gravida lorem non erat mattis ac aliquam augue ullamcorper. Cras vel suscipit lorem. Nulla facilisi. Duis ut est enim, sed tempus massa. Praesent massa eros, egestas ut tincidunt vel, elementum vitae libero. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae. Donec ut semper enim. In pellentesque malesuada adipiscing. Cras ullamcorper urna sed leo iaculis molestie. Proin urna ipsum, congue ut dignissim ut, consectetur id sem. Nulla felis dui, fringilla suscipit dapibus non, mattis ut lectus. Suspendisse potenti. Quisque porttitor porttitor cursus.' },
        { group: sampleGroups[0], backgroundColor: '#ffd800', imageUrl: '', subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit', description: 'Donec elementum ipsum nunc, sit amet placerat lacus. Etiam eu rutrum quam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam tempor, urna sed ullamcorper volutpat, libero orci malesuada lacus, ut fringilla enim mi sed eros. Cras sit amet massa eu mauris accumsan semper eget et massa. In eget ipsum a mi elementum molestie. Ut facilisis orci eget leo pretium ut iaculis lorem mattis. Praesent nec leo a metus euismod suscipit quis at tortor. Nulla ut justo leo, id luctus orci. Aliquam nec enim eget enim aliquam mattis sed et purus. Integer gravida lorem non erat mattis ac aliquam augue ullamcorper. Cras vel suscipit lorem. Nulla facilisi. Duis ut est enim, sed tempus massa. Praesent massa eros, egestas ut tincidunt vel, elementum vitae libero. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae. Donec ut semper enim. In pellentesque malesuada adipiscing. Cras ullamcorper urna sed leo iaculis molestie. Proin urna ipsum, congue ut dignissim ut, consectetur id sem. Nulla felis dui, fringilla suscipit dapibus non, mattis ut lectus. Suspendisse potenti. Quisque porttitor porttitor cursus.' },
        { group: sampleGroups[0], backgroundColor: '#0094ff', imageUrl: '', subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit', description: 'Donec elementum ipsum nunc, sit amet placerat lacus. Etiam eu rutrum quam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam tempor, urna sed ullamcorper volutpat, libero orci malesuada lacus, ut fringilla enim mi sed eros. Cras sit amet massa eu mauris accumsan semper eget et massa. In eget ipsum a mi elementum molestie. Ut facilisis orci eget leo pretium ut iaculis lorem mattis. Praesent nec leo a metus euismod suscipit quis at tortor. Nulla ut justo leo, id luctus orci. Aliquam nec enim eget enim aliquam mattis sed et purus. Integer gravida lorem non erat mattis ac aliquam augue ullamcorper. Cras vel suscipit lorem. Nulla facilisi. Duis ut est enim, sed tempus massa. Praesent massa eros, egestas ut tincidunt vel, elementum vitae libero. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae. Donec ut semper enim. In pellentesque malesuada adipiscing. Cras ullamcorper urna sed leo iaculis molestie. Proin urna ipsum, congue ut dignissim ut, consectetur id sem. Nulla felis dui, fringilla suscipit dapibus non, mattis ut lectus. Suspendisse potenti. Quisque porttitor porttitor cursus.' },
        { group: sampleGroups[0], backgroundColor: '#b200ff', imageUrl: '', subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit', description: 'Donec elementum ipsum nunc, sit amet placerat lacus. Etiam eu rutrum quam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam tempor, urna sed ullamcorper volutpat, libero orci malesuada lacus, ut fringilla enim mi sed eros. Cras sit amet massa eu mauris accumsan semper eget et massa. In eget ipsum a mi elementum molestie. Ut facilisis orci eget leo pretium ut iaculis lorem mattis. Praesent nec leo a metus euismod suscipit quis at tortor. Nulla ut justo leo, id luctus orci. Aliquam nec enim eget enim aliquam mattis sed et purus. Integer gravida lorem non erat mattis ac aliquam augue ullamcorper. Cras vel suscipit lorem. Nulla facilisi. Duis ut est enim, sed tempus massa. Praesent massa eros, egestas ut tincidunt vel, elementum vitae libero. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae. Donec ut semper enim. In pellentesque malesuada adipiscing. Cras ullamcorper urna sed leo iaculis molestie. Proin urna ipsum, congue ut dignissim ut, consectetur id sem. Nulla felis dui, fringilla suscipit dapibus non, mattis ut lectus. Suspendisse potenti. Quisque porttitor porttitor cursus.' },

        { group: sampleGroups[1], backgroundColor: '#16db30', imageUrl: '/images/mostRead/mostRead1.jpg', subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit', description: 'Donec elementum ipsum nunc, sit amet placerat lacus. Etiam eu rutrum quam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam tempor, urna sed ullamcorper volutpat, libero orci malesuada lacus, ut fringilla enim mi sed eros. Cras sit amet massa eu mauris accumsan semper eget et massa. In eget ipsum a mi elementum molestie. Ut facilisis orci eget leo pretium ut iaculis lorem mattis. Praesent nec leo a metus euismod suscipit quis at tortor. Nulla ut justo leo, id luctus orci. Aliquam nec enim eget enim aliquam mattis sed et purus. Integer gravida lorem non erat mattis ac aliquam augue ullamcorper. Cras vel suscipit lorem. Nulla facilisi. Duis ut est enim, sed tempus massa. Praesent massa eros, egestas ut tincidunt vel, elementum vitae libero. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae. Donec ut semper enim. In pellentesque malesuada adipiscing. Cras ullamcorper urna sed leo iaculis molestie. Proin urna ipsum, congue ut dignissim ut, consectetur id sem. Nulla felis dui, fringilla suscipit dapibus non, mattis ut lectus. Suspendisse potenti. Quisque porttitor porttitor cursus.' },
        { group: sampleGroups[1], backgroundColor: '#f00', imageUrl: '/images/mostRead/mostRead2.jpg', subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit', description: 'Donec elementum ipsum nunc, sit amet placerat lacus. Etiam eu rutrum quam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam tempor, urna sed ullamcorper volutpat, libero orci malesuada lacus, ut fringilla enim mi sed eros. Cras sit amet massa eu mauris accumsan semper eget et massa. In eget ipsum a mi elementum molestie. Ut facilisis orci eget leo pretium ut iaculis lorem mattis. Praesent nec leo a metus euismod suscipit quis at tortor. Nulla ut justo leo, id luctus orci. Aliquam nec enim eget enim aliquam mattis sed et purus. Integer gravida lorem non erat mattis ac aliquam augue ullamcorper. Cras vel suscipit lorem. Nulla facilisi. Duis ut est enim, sed tempus massa. Praesent massa eros, egestas ut tincidunt vel, elementum vitae libero. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae. Donec ut semper enim. In pellentesque malesuada adipiscing. Cras ullamcorper urna sed leo iaculis molestie. Proin urna ipsum, congue ut dignissim ut, consectetur id sem. Nulla felis dui, fringilla suscipit dapibus non, mattis ut lectus. Suspendisse potenti. Quisque porttitor porttitor cursus.' },
        { group: sampleGroups[1], backgroundColor: '#c21d12', imageUrl: '/images/mostRead/mostRead3.jpg', subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit', description: 'Donec elementum ipsum nunc, sit amet placerat lacus. Etiam eu rutrum quam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam tempor, urna sed ullamcorper volutpat, libero orci malesuada lacus, ut fringilla enim mi sed eros. Cras sit amet massa eu mauris accumsan semper eget et massa. In eget ipsum a mi elementum molestie. Ut facilisis orci eget leo pretium ut iaculis lorem mattis. Praesent nec leo a metus euismod suscipit quis at tortor. Nulla ut justo leo, id luctus orci. Aliquam nec enim eget enim aliquam mattis sed et purus. Integer gravida lorem non erat mattis ac aliquam augue ullamcorper. Cras vel suscipit lorem. Nulla facilisi. Duis ut est enim, sed tempus massa. Praesent massa eros, egestas ut tincidunt vel, elementum vitae libero. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae. Donec ut semper enim. In pellentesque malesuada adipiscing. Cras ullamcorper urna sed leo iaculis molestie. Proin urna ipsum, congue ut dignissim ut, consectetur id sem. Nulla felis dui, fringilla suscipit dapibus non, mattis ut lectus. Suspendisse potenti. Quisque porttitor porttitor cursus.' },
        { group: sampleGroups[1], backgroundColor: '#0026ff', imageUrl: '/images/mostRead/mostRead4.jpg', subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit', description: 'Donec elementum ipsum nunc, sit amet placerat lacus. Etiam eu rutrum quam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam tempor, urna sed ullamcorper volutpat, libero orci malesuada lacus, ut fringilla enim mi sed eros. Cras sit amet massa eu mauris accumsan semper eget et massa. In eget ipsum a mi elementum molestie. Ut facilisis orci eget leo pretium ut iaculis lorem mattis. Praesent nec leo a metus euismod suscipit quis at tortor. Nulla ut justo leo, id luctus orci. Aliquam nec enim eget enim aliquam mattis sed et purus. Integer gravida lorem non erat mattis ac aliquam augue ullamcorper. Cras vel suscipit lorem. Nulla facilisi. Duis ut est enim, sed tempus massa. Praesent massa eros, egestas ut tincidunt vel, elementum vitae libero. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae. Donec ut semper enim. In pellentesque malesuada adipiscing. Cras ullamcorper urna sed leo iaculis molestie. Proin urna ipsum, congue ut dignissim ut, consectetur id sem. Nulla felis dui, fringilla suscipit dapibus non, mattis ut lectus. Suspendisse potenti. Quisque porttitor porttitor cursus.' },

        { group: sampleGroups[2], backgroundColor: '#b2aac2', imageUrl: '/images/recentActivity/people1.jpg', subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit', description: 'Donec elementum ipsum nunc, sit amet placerat lacus. Etiam eu rutrum quam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam tempor, urna sed ullamcorper volutpat, libero orci malesuada lacus, ut fringilla enim mi sed eros. Cras sit amet massa eu mauris accumsan semper eget et massa. In eget ipsum a mi elementum molestie. Ut facilisis orci eget leo pretium ut iaculis lorem mattis. Praesent nec leo a metus euismod suscipit quis at tortor. Nulla ut justo leo, id luctus orci. Aliquam nec enim eget enim aliquam mattis sed et purus. Integer gravida lorem non erat mattis ac aliquam augue ullamcorper. Cras vel suscipit lorem. Nulla facilisi. Duis ut est enim, sed tempus massa. Praesent massa eros, egestas ut tincidunt vel, elementum vitae libero. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae. Donec ut semper enim. In pellentesque malesuada adipiscing. Cras ullamcorper urna sed leo iaculis molestie. Proin urna ipsum, congue ut dignissim ut, consectetur id sem. Nulla felis dui, fringilla suscipit dapibus non, mattis ut lectus. Suspendisse potenti. Quisque porttitor porttitor cursus.' },
        { group: sampleGroups[2], backgroundColor: '#4800ff', imageUrl: '/images/recentActivity/people2.jpg', subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit', description: 'Donec elementum ipsum nunc, sit amet placerat lacus. Etiam eu rutrum quam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam tempor, urna sed ullamcorper volutpat, libero orci malesuada lacus, ut fringilla enim mi sed eros. Cras sit amet massa eu mauris accumsan semper eget et massa. In eget ipsum a mi elementum molestie. Ut facilisis orci eget leo pretium ut iaculis lorem mattis. Praesent nec leo a metus euismod suscipit quis at tortor. Nulla ut justo leo, id luctus orci. Aliquam nec enim eget enim aliquam mattis sed et purus. Integer gravida lorem non erat mattis ac aliquam augue ullamcorper. Cras vel suscipit lorem. Nulla facilisi. Duis ut est enim, sed tempus massa. Praesent massa eros, egestas ut tincidunt vel, elementum vitae libero. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae. Donec ut semper enim. In pellentesque malesuada adipiscing. Cras ullamcorper urna sed leo iaculis molestie. Proin urna ipsum, congue ut dignissim ut, consectetur id sem. Nulla felis dui, fringilla suscipit dapibus non, mattis ut lectus. Suspendisse potenti. Quisque porttitor porttitor cursus.' },

        { group: sampleGroups[3], backgroundColor: '#12caff', imageUrl: '/images/theWeek/theWeek1.jpg', subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit', description: 'Donec elementum ipsum nunc, sit amet placerat lacus. Etiam eu rutrum quam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam tempor, urna sed ullamcorper volutpat, libero orci malesuada lacus, ut fringilla enim mi sed eros. Cras sit amet massa eu mauris accumsan semper eget et massa. In eget ipsum a mi elementum molestie. Ut facilisis orci eget leo pretium ut iaculis lorem mattis. Praesent nec leo a metus euismod suscipit quis at tortor. Nulla ut justo leo, id luctus orci. Aliquam nec enim eget enim aliquam mattis sed et purus. Integer gravida lorem non erat mattis ac aliquam augue ullamcorper. Cras vel suscipit lorem. Nulla facilisi. Duis ut est enim, sed tempus massa. Praesent massa eros, egestas ut tincidunt vel, elementum vitae libero. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae. Donec ut semper enim. In pellentesque malesuada adipiscing. Cras ullamcorper urna sed leo iaculis molestie. Proin urna ipsum, congue ut dignissim ut, consectetur id sem. Nulla felis dui, fringilla suscipit dapibus non, mattis ut lectus. Suspendisse potenti. Quisque porttitor porttitor cursus.' },
        { group: sampleGroups[3], backgroundColor: '#f4fe0d', imageUrl: '/images/theWeek/theWeek2.jpg', subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit', description: 'Donec elementum ipsum nunc, sit amet placerat lacus. Etiam eu rutrum quam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam tempor, urna sed ullamcorper volutpat, libero orci malesuada lacus, ut fringilla enim mi sed eros. Cras sit amet massa eu mauris accumsan semper eget et massa. In eget ipsum a mi elementum molestie. Ut facilisis orci eget leo pretium ut iaculis lorem mattis. Praesent nec leo a metus euismod suscipit quis at tortor. Nulla ut justo leo, id luctus orci. Aliquam nec enim eget enim aliquam mattis sed et purus. Integer gravida lorem non erat mattis ac aliquam augue ullamcorper. Cras vel suscipit lorem. Nulla facilisi. Duis ut est enim, sed tempus massa. Praesent massa eros, egestas ut tincidunt vel, elementum vitae libero. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae. Donec ut semper enim. In pellentesque malesuada adipiscing. Cras ullamcorper urna sed leo iaculis molestie. Proin urna ipsum, congue ut dignissim ut, consectetur id sem. Nulla felis dui, fringilla suscipit dapibus non, mattis ut lectus. Suspendisse potenti. Quisque porttitor porttitor cursus.' },
        { group: sampleGroups[3], backgroundColor: '#00ff21', imageUrl: '/images/theWeek/theWeek3.jpg', subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit', description: 'Donec elementum ipsum nunc, sit amet placerat lacus. Etiam eu rutrum quam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam tempor, urna sed ullamcorper volutpat, libero orci malesuada lacus, ut fringilla enim mi sed eros. Cras sit amet massa eu mauris accumsan semper eget et massa. In eget ipsum a mi elementum molestie. Ut facilisis orci eget leo pretium ut iaculis lorem mattis. Praesent nec leo a metus euismod suscipit quis at tortor. Nulla ut justo leo, id luctus orci. Aliquam nec enim eget enim aliquam mattis sed et purus. Integer gravida lorem non erat mattis ac aliquam augue ullamcorper. Cras vel suscipit lorem. Nulla facilisi. Duis ut est enim, sed tempus massa. Praesent massa eros, egestas ut tincidunt vel, elementum vitae libero. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae. Donec ut semper enim. In pellentesque malesuada adipiscing. Cras ullamcorper urna sed leo iaculis molestie. Proin urna ipsum, congue ut dignissim ut, consectetur id sem. Nulla felis dui, fringilla suscipit dapibus non, mattis ut lectus. Suspendisse potenti. Quisque porttitor porttitor cursus.' },
        { group: sampleGroups[3], backgroundColor: '#082941', imageUrl: '/images/theWeek/theWeek4.jpg', subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit', description: 'Donec elementum ipsum nunc, sit amet placerat lacus. Etiam eu rutrum quam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam tempor, urna sed ullamcorper volutpat, libero orci malesuada lacus, ut fringilla enim mi sed eros. Cras sit amet massa eu mauris accumsan semper eget et massa. In eget ipsum a mi elementum molestie. Ut facilisis orci eget leo pretium ut iaculis lorem mattis. Praesent nec leo a metus euismod suscipit quis at tortor. Nulla ut justo leo, id luctus orci. Aliquam nec enim eget enim aliquam mattis sed et purus. Integer gravida lorem non erat mattis ac aliquam augue ullamcorper. Cras vel suscipit lorem. Nulla facilisi. Duis ut est enim, sed tempus massa. Praesent massa eros, egestas ut tincidunt vel, elementum vitae libero. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae. Donec ut semper enim. In pellentesque malesuada adipiscing. Cras ullamcorper urna sed leo iaculis molestie. Proin urna ipsum, congue ut dignissim ut, consectetur id sem. Nulla felis dui, fringilla suscipit dapibus non, mattis ut lectus. Suspendisse potenti. Quisque porttitor porttitor cursus.' },
        { group: sampleGroups[3], backgroundColor: '#0094ff', imageUrl: '/images/theWeek/theWeek5.jpg', subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit', description: 'Donec elementum ipsum nunc, sit amet placerat lacus. Etiam eu rutrum quam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam tempor, urna sed ullamcorper volutpat, libero orci malesuada lacus, ut fringilla enim mi sed eros. Cras sit amet massa eu mauris accumsan semper eget et massa. In eget ipsum a mi elementum molestie. Ut facilisis orci eget leo pretium ut iaculis lorem mattis. Praesent nec leo a metus euismod suscipit quis at tortor. Nulla ut justo leo, id luctus orci. Aliquam nec enim eget enim aliquam mattis sed et purus. Integer gravida lorem non erat mattis ac aliquam augue ullamcorper. Cras vel suscipit lorem. Nulla facilisi. Duis ut est enim, sed tempus massa. Praesent massa eros, egestas ut tincidunt vel, elementum vitae libero. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae. Donec ut semper enim. In pellentesque malesuada adipiscing. Cras ullamcorper urna sed leo iaculis molestie. Proin urna ipsum, congue ut dignissim ut, consectetur id sem. Nulla felis dui, fringilla suscipit dapibus non, mattis ut lectus. Suspendisse potenti. Quisque porttitor porttitor cursus.' },
        { group: sampleGroups[3], backgroundColor: '#004050', imageUrl: '/images/theWeek/theWeek6.jpg', subtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit', description: 'Donec elementum ipsum nunc, sit amet placerat lacus. Etiam eu rutrum quam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam tempor, urna sed ullamcorper volutpat, libero orci malesuada lacus, ut fringilla enim mi sed eros. Cras sit amet massa eu mauris accumsan semper eget et massa. In eget ipsum a mi elementum molestie. Ut facilisis orci eget leo pretium ut iaculis lorem mattis. Praesent nec leo a metus euismod suscipit quis at tortor. Nulla ut justo leo, id luctus orci. Aliquam nec enim eget enim aliquam mattis sed et purus. Integer gravida lorem non erat mattis ac aliquam augue ullamcorper. Cras vel suscipit lorem. Nulla facilisi. Duis ut est enim, sed tempus massa. Praesent massa eros, egestas ut tincidunt vel, elementum vitae libero. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae. Donec ut semper enim. In pellentesque malesuada adipiscing. Cras ullamcorper urna sed leo iaculis molestie. Proin urna ipsum, congue ut dignissim ut, consectetur id sem. Nulla felis dui, fringilla suscipit dapibus non, mattis ut lectus. Suspendisse potenti. Quisque porttitor porttitor cursus.' },
        
    ];

    // Get a reference for an item, using the group key and item title as a
    // unique reference to the item that can be easily serialized.
    function getItemReference(item) {
        return [item.group.key, item.title];
    }

    function resolveGroupReference(key) {
        for (var i = 0; i < groupedItems.groups.length; i++) {
            if (groupedItems.groups.getAt(i).key === key) {
                return groupedItems.groups.getAt(i);
            }
        }
    }

    function resolveItemReference(reference) {
        for (var i = 0; i < groupedItems.length; i++) {
            var item = groupedItems.getAt(i);
            if (item.group.key === reference[0] && item.title === reference[1]) {
                return item;
            }
        }
    }

    // This function returns a WinJS.Binding.List containing only the items
    // that belong to the provided group.
    function getItemsFromGroup(group) {
        return list.createFiltered(function (item) { return item.group.key === group.key; });
    }

    var list = new WinJS.Binding.List();
    var groupedItems = list.createGrouped(
        function groupKeySelector(item) { return item.group.key; },
        function groupDataSelector(item) { return item.group; }
    );

    // TODO: Replace the data with your real data.
    // You can add data from asynchronous sources whenever it becomes available.
    sampleItems.forEach(function (item) {
        list.push(item);
    });

    WinJS.Namespace.define("Data", {
        items: groupedItems,
        groups: groupedItems.groups,
        getItemsFromGroup: getItemsFromGroup,
        getItemReference: getItemReference,
        resolveGroupReference: resolveGroupReference,
        resolveItemReference: resolveItemReference
    });
})();
